### ISSUE TITLE
Create SSH Scraper script

### ISSUE THREAD

**Issue by Poggecci** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#15]
In order to procure data about section times and course availability without requiring extensive amounts of user input, we will utilize UPRM's SSH server (accessed through a terminal with `ssh estudiante@rumad.uprm.edu` ).

Create a program to read in credentials from a json file passed in as an argument alongside a course (ie: INSO4116)
and utilizes that information to return a structured representation of all the section data.

The program must be asynchronous, avoid getting stuck, exit after a configurable amount of time passes, and handle all common cases like: no sections available, multiple pages of sections, connection failed, etc.

**Comment by KelvinGonzalez** [comment]
Linked issues:
#24, #25

**Comment by KelvinGonzalez** [comment]
[PRD](https://docs.google.com/document/d/1GpjOzsQV4POcTCz2lNUCEtGoQIFBtoVCCNjnY5Ifs98/edit?usp=sharing)
