### ISSUE TITLE
Fixing and clarifying what the statement "The system must be capable of processing requests to create user profiles in under 200 ms while under normal conditions." really means

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#168]
Specify what simultaneous really means(define the scenario better) and clear other doubts

Marko's feedback:
"The system must be capable of processing requests to create user profiles in under 200 ms while under normal conditions." is duplicated, but with complementary explanation for what normal conditions are. 100 users sending requests simultaneously is not a very good measure or condition. What does simultaneously really mean? Do these requests have to be sent within the same minute, second, milli-second, micro-second,...? What's the right resolution here? It's a better idea to define some standard scenarios (student creating profile, student planning next semester's enrollment, student preparing scholarship application, etc.) and then to define normal conditions in terms of a random weighted mix of these scenarios started as random times during, say, one minute. Then weaken the requirement to: the system must process requests to create profiles in under 200ms in 98% of normal conditions. (Since you randomize, there might be some very strange loads generated where e.g. all the scenarios even start within the first micro-second and then some might take longer from the time they started until they complete)

**Comment by GabrielGranell15** [comment]
Changed "The system must be capable of processing requests to create user profiles in under 200 ms while under normal conditions.
Normal conditions are defined as a server load of 5 QPS
The system must be capable of processing requests to create user profiles in under 200 ms while under normal conditions.
Normal conditions are defined as 100 users simultaneously sending requests to the platform." to "The system must process requests to create user profiles in under 200 ms in 98% of normal conditions. 
Normal conditions are defined as a random weighted mix of standard scenarios, such as a student creating a profile, a student planning the next semester's enrollment, and a student preparing a scholarship application. 
These scenarios are initiated at random times during a one-minute interval.
The system's performance should be evaluated across different times of the day to account for potential fluctuations in user activity. 
Furthermore, the assessment should consider variations in data input sizes, ensuring that the system maintains the defined processing time even with varying complexities of user profiles." to allow for variation regarding different scenarios a user might do that may affect request processing.
