### ISSUE TITLE
Clear doubts on deployment strategy

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#171]
Marko's feedback: 
For the deployment strategy: where will the docker containers be hosted? Why splitting it up like this, e.g. two containers not one? If there was debate about this, if the distribution was not clear from the start, then alternatives can be shown and discussed in the analytic part and that part can be referred to from here.

**Comment by Poggecci** [comment]
Archiving as it is a duplicate
