### ISSUE TITLE
Fix a statement in course query PRD

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#180]
Marko's feedback:
On your course query PRD, "Users shall input queries following a specified syntax defined by the context-free grammar." is not a requirement, since it doesn't require anything of the system-to-be. One could say it's a business process reengineering requirement, so not a requirement on the system-to-be, but a requirement on the environment in which the system-to-be will operate.

**Comment by KelvinGonzalez** [comment]
Deleted specified requirement from the CQL PRD, corrected requirement was already included under query parsing requirements: "The application shall parse user queries according to the defined context-free grammar."
