### ISSUE TITLE
Clear doubts for credit acquisition for undergraduate degrees, graduate courses and transfer of credits

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#181]
Marko's feedback:
In most undergraduate programs students can take some number of graduate courses. Whether or not they can, how they get credit for them (can they take the credit towards their undergraduate degree? Can they then still get credit for the course once they start graduate school?...) is up to the regulations of the school.

**Comment by AlonsoUriarte14** [comment]
Repeated issue #187 ; already handled.
