### ISSUE TITLE
[Doc Feedback] Clarify "Users shall input queries following a specified syntax defined by the context-free grammar." as a business process reengineering requirement.

### ISSUE THREAD

**Issue by EdwinC1339** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#188]

**Comment by KelvinGonzalez** [comment]
Deleted specified requirement from the CQL PRD, corrected requirement was already included under query parsing requirements: "The application shall parse user queries according to the defined context-free grammar."
