### ISSUE TITLE
[Doc Feedback] Enrich personas

### ISSUE THREAD

**Issue by EdwinC1339** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#190]

**Comment by JannGarcia** [comment]
@EdwinC1339 @JeremySanchez1 

Is there a difference between this issue and [the other one we were assigned to](https://github.com/uprm-inso4116-2023-2024-S1/semester-project-college-toolbox/issues/166)? They both seem to cover the same idea of improving the personas overall, so having 2 issues doesn't make sense to me.

**Comment by JannGarcia** [comment]
Talked w/ @JeremySanchez1 about this. This is a duplicate issue. Gonna mark as closed. :)
