### ISSUE TITLE
[Doc Feedback] Revise machine requirement to process requests to create user profiles (details in description)

### ISSUE THREAD

**Issue by EdwinC1339** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#200]
"The system must be capable of processing requests to create user profiles in under 200 ms while under normal conditions." is duplicated, but with complementary explanation for what normal conditions are. 100 users sending requests simultaneously is not a very good measure or condition. What does simultaneously really mean? Do these requests have to be sent within the same minute, second, milli-second, micro-second,...? What's the right resolution here? It's a better idea to define some standard scenarios (student creating profile, student planning next semester's enrollment, student preparing scholarship application, etc.) and then to define normal conditions in terms of a random weighted mix of these scenarios started as random times during, say, one minute. Then weaken the requirement to: the system must process requests to create profiles in under 200ms in 98% of normal conditions. (Since you randomize, there might be some very strange loads generated where e.g. all the scenarios even start within the first micro-second and then some might take longer from the time they started until they complete)

**Comment by GabrielGranell15** [comment]
fixed in issue #168
