### ISSUE TITLE
Add colors to courses in Tuition Scheduler

### ISSUE THREAD

**Issue by Juliam-Rodriguez** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#228]
Colors blocks for courses are set default to blue, make it so all courses have their unique color

**Comment by Juliam-Rodriguez** [comment]
![Image](https://github.com/uprm-inso4116-2023-2024-S1/semester-project-college-toolbox/assets/78494322/a1ba81e6-342e-46d2-848e-9add5677c326)



![Image](https://github.com/uprm-inso4116-2023-2024-S1/semester-project-college-toolbox/assets/78494322/655c1b59-e536-428b-b712-4a9a9082d405)

This is how it looks like now

**Comment by JeremySanchez1** [comment]
- [ ] Dark mode styling
- [ ] Colors don't repeat in the same schedule
- [ ] course code uniformity between schedules
