### ISSUE TITLE
[Lecture Topic Task] Establish a shared vocabulary for filter-related terms, working closely with developers and users to define terms like "accepted," "denied," and "waiting status" consistently across the scholarship status and date filters.

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#264]
This is for Ubiquitous Language
This is for Scholarship Status Filter and Scholarship Date Filter feature

**Comment by GabrielGranell15** [comment]
This was already implemented. Terms and vocabulary have been defined to be easy to understand for Users, as well as remain consistant
