### ISSUE TITLE
[Lecture Topic Task]  Establish a consistent interface for representing existing solutions in the information hub. Guarantee that adding or modifying existing solutions doesn't break the ability to display and interact with these solutions in a uniform manner.

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#266]
This is for Liskov Substitution
This is for Existing Solutions feature

**Comment by DevSebastian1** [comment]
I've gone over the code and there doesn't **seem** to be a way to apply Liskov Substitution.

**Comment by Adrian-OCS** [comment]
Agreeing with @DevSebastian1 , there are no subclasses for this "ExistingSolution" superclass, and thus it's impossible to check if the subclasses can be replaced by the superclass (Liskov Substitution).
