### ISSUE TITLE
[Tuition Scheduler] Create modal view for saved schedules

### ISSUE THREAD

**Issue by JeremySanchez1** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#289]
![Image](https://github.com/uprm-inso4116-2023-2024-S1/semester-project-college-toolbox/assets/71047020/354add26-ab99-473c-a36f-3330d6f6a509)

**Comment by Juliam-Rodriguez** [comment]
Current:


![Image](https://github.com/uprm-inso4116-2023-2024-S1/semester-project-college-toolbox/assets/78494322/e9de0813-94f6-4dc4-bf91-413efd587d20)



![Image](https://github.com/uprm-inso4116-2023-2024-S1/semester-project-college-toolbox/assets/78494322/103a02ff-5d8c-4d60-b40e-e5c523788a87)
