### ISSUE TITLE
[Lecture Topic Task] Identify the side effects in Scholarship Application Helper code and refactor them out

### ISSUE THREAD

**Issue by Ryan8702** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#293]

**Comment by Ryan8702** [comment]
Multiple people can participate in this task

**Comment by GabrielGranell15** [comment]
Identified side effects
- Counter calculation and updates
- DeadlineDate
- Updating the status

**Comment by GabrielGranell15** [comment]
Current side effects have been resolved by refactoring. Future refactoring will be considered before submitting new implementations.
