### ISSUE TITLE
[Lecture Topic Task] Intention revealing interfaces

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#303]
The team shows examples where they originally had an interface that was not very intention revealing and then they worked toward making it more intention revealing.

[Should show the initial situation before that application, how and why the technique can be applied maybe discussing different options. Then applying the technique, pattern, tool…, presenting the result, and explaining the improvement to the previous version.]

**Comment by Robert-6** [comment]
only did this for the scholarship and job app side I saw it was also done for the other sides of the project not sure who was working on that though feel free to assign this issue to whoever it was as well
