### ISSUE TITLE
[Lecture Topic Task] Stand-alone classes

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#307]
The team shows examples where initially they had a class with several dependencies and then they worked towards making these dependencies unnecessary so they could drop them. This might involve the use of other patterns.

[Should show the initial situation before that application, how and why the technique can be applied maybe discussing different options. Then applying the technique, pattern, tool…, presenting the result, and explaining the improvement to the previous version.]

**Comment by JannGarcia** [comment]
https://docs.google.com/document/d/1LVdz-JcBD8_61pZO3taUbAPlnM9BB_HKTgOTg0Gm0Lw/edit#heading=h.v13xvrvqws1m

Here's the heading to the documentation pertaining to this issue
