### ISSUE TITLE
[Lecture Topic Task] Other patterns

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#309]
The team shows examples of at least one other pattern (composite, transaction,…)  from the analysis patterns discussed in class. 

An example would be locations within locations. Just for example, say we wanted to state where within an super market chain an item is located. We could have an initial "locator" indicating the individual store of the chain in which the item is located. Below that we might have a locator that indicates a location within the store, say the high level area (storage, shelves, unloading dock,…). Then some of these might contain another level of sub-division. For example, shelves divided into aisles, aisles into sections, sections into floors

[Should show the initial situation before that application, how and why the technique can be applied maybe discussing different options. Then applying the technique, pattern, tool…, presenting the result, and explaining the improvement to the previous version.]

**Comment by AcevedoC17** [comment]
Added to the documentation under section 5.10.
