### ISSUE TITLE
FE branch scholarshiptracker's navbar is not displaying correctly on Firefox

### ISSUE THREAD

**Issue by EdwinC1339** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#45]
![Image](https://github.com/uprm-inso4116-2023-2024-S1/semester-project-college-toolbox/assets/90163465/b843506d-9c09-4f8c-84b2-923259768a5c)

Styling was fine on main branch, displays as white and washed out when checked into scholarshiptracker branch.

**Comment by GabrielGranell15** [comment]
![image](https://github.com/uprm-inso4116-2023-2024-S1/semester-project-college-toolbox/assets/89162625/f3af70d7-c907-471d-b196-9cc9e1a861d2)
A unused import of bootstrap was causing the issue. It is now fixed.

**Comment by GabrielGranell15** [comment]
![image](https://github.com/uprm-inso4116-2023-2024-S1/semester-project-college-toolbox/assets/89162625/f0f7484d-2402-41be-b7a4-1018b8f9bf95)
A unused import of bootstrap in the index. astro file was causing the bug. It has been removed and issue has been fixed.
